from functools import partial

from django.conf import settings

from document_map_viewer.commons import Point

get_setting = partial(getattr, settings)

# URL Parameters
URL_PARAMETER_NAME_FORMAT = 'format'
URL_PARAMETER_NAME_HITS_PER_PAGE = 'hitsPerPage'
URL_PARAMETER_NAME_LATITUDE = 'lat'
URL_PARAMETER_NAME_LONGITUDE = 'lon'
URL_PARAMETER_NAME_RADIUS = 'radius'
URL_PARAMETER_NAME_RESUME_TOKEN = 'resumeToken'
URL_PARAMETER_NAME_YEAR_END = 'yearEnd'
URL_PARAMETER_NAME_YEAR_START = 'yearStart'
URL_PARAMETER_NAME_TERM = 'term'


# Spatial Database Configuration
MAP_VIEWER_SOLR_SPATIAL_DATABASE_HOSTNAME = get_setting('MAP_VIEWER_SOLR_SPATIAL_DATABASE_HOSTNAME', None)
MAP_VIEWER_SOLR_GEOSPATIAL_FIELD_NAME = get_setting('MAP_VIEWER_SOLR_GEOSPATIAL_FIELD_NAME', None)
MAP_VIEWER_SOLR_GEOJSON_DATA_FIELD_NAME = get_setting('MAP_VIEWER_SOLR_GEOJSON_DATA_FIELD_NAME', None)

# Spatial Database Configuration Parameters
DATABASE_HOSTNAME_CONFIGURATION_NAME = 'url'

# Solr Query Default Values
SOLR_DEFAULT_VALUE_CURSOR = '*'
SOLR_DEFAULT_VALUE_DATE_SPAN = '[* TO NOW]'
SOLR_DEFAULT_VALUE_HITS_PER_PAGE = '100'
SOLR_DEFAULT_VALUE_RADIUS = 50
SOLR_DEFAULT_VALUE_RETURN_FIELDS = MAP_VIEWER_SOLR_GEOJSON_DATA_FIELD_NAME
SOLR_DEFAULT_VALUE_SPATIAL_CENTER = Point(latitude=51.16336, longitude=10.44768)
